### ISSUE TITLE
Set up Discord for 130

### ISSUE THREAD

**Issue by njlytal** [norcalbiostat/MATH130#26]
NOTE: Investigate bots that can add roles as well.

**Comment by norcalbiostat** [comment]
in progress! talking with the computer science student discord mods atm to get best practices/their setup.

**Comment by norcalbiostat** [comment]
perpetual invite link: https://discord.gg/ck497bJty5 
putting it in the syllabus. no roles set yet

**Comment by norcalbiostat** [comment]
Need to create video walk through on how to create/use discord. I've deleted my @mail.csuchico.edu account and so will make this video in 2 wks after it's actually toast (and we have the server more setup)

**Comment by norcalbiostat** [comment]
server created, will need to work on how we introduce it to our students.
