### ISSUE TITLE
My students are finding the discussion on `class()` confusing

### ISSUE THREAD

**Issue by roualdes** [norcalbiostat/MATH130#8]
So early in the semester, I'm just starting to get students used to categorical and numerical variables.  These are common statistics words.

But hw1 blends these statistics words with some computer science words: character, logical.  Of course these words are good, too, just maybe introduced too early.  For a statistics course, it seems to me that we should start with just the absolutely crucial statistics words.  Later on, we could introduce nuances.

What do you think?

Tangent. Also, factor is left out.  Which seems more important to me than character or logical.

**Comment by norcalbiostat** [comment]
I hear what you're saying. 
I can add a short piece on categorical vs numerical before getting into how R classifies data types. Totally reasonable. 

Re factors: You're right that factors are only mentioned as an off hand in lec04, but are important enough to have an entire lecture (06) devoted to them. I could add a little more of an introduction in lec04 in data types, something along the lines of showing how R sees categorical variables as either factors or characters. 

Regarding putting off characters and logicals past lecture4/hw1: The way that is shown how to subset and recoding data is using logical statements so i'm not sure that it could be put off until later.

**Comment by roualdes** [comment]
Thanks.  And fair.

**Comment by roualdes** [comment]
Thanks for adding in some words to lec04 about this, re PR #34.
